.

diff --git a/pwd.yml b/pwd.yml
--- a/pwd.yml
+++ b/pwd.yml
@@ -75,7 +75,7 @@ services:
     networks:
       - erp-network
 
-  create-site:
+  create-site-erp:
     image: frappe/erpnext:v15.10.7
     depends_on:
       db:
@@ -107,9 +107,53 @@ services:
           fi
         done;
         echo "sites/common_site_config.json found";
-        bench get-app non_profit
+        echo "Getting app webshop";
+        bench get-app webshop
+        echo "Getting app payments";
         bench get-app payments
-        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default erp;
+        echo "Creating site erp";
+        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --install-app webshop --install-app payments --set-default erp;
+    networks:
+      - mariadb-network
+      - erp-network
+
+  create-site-morsy:
+    image: frappe/erpnext:v15.10.7
+    depends_on:
+      db:
+        condition: service_healthy
+    deploy:
+      restart_policy:
+        condition: none
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        echo "Getting app non_profit";
+        bench get-app non_profit
+        echo "Getting app payments";
+        bench get-app payments
+        echo "Creating site morsy";
         bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --install-app non_profit --install-app payments --set-default morsy;
     networks:
       - mariadb-network
